SELECT b.AUTHOR_ID, a.AUTHOR_NAME, b.CATEGORY, SUM(b.PRICE * s.SALES) as TOTAL_SALES
FROM BOOK b, AUTHOR a, BOOK_SALES s
WHERE b.AUTHOR_ID = a.AUTHOR_ID and b.BOOK_ID = s.BOOK_ID and YEAR(s.SALES_DATE) = 2022 and MONTH(s.SALES_DATE) = 1
GROUP BY b.AUTHOR_ID, b.CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC