SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO a
WHERE FAVORITES = (SELECT MAX(FAVORITES) FROM REST_INFO b WHERE a.FOOD_TYPE = b.FOOD_TYPE GROUP BY FOOD_TYPE)
GROUP BY FOOD_TYPE
ORDER BY FOOD_TYPE DESC