SELECT YEAR(SALES_DATE) as YEAR, MONTH(SALES_DATE) as MONTH, GENDER, COUNT(DISTINCT s.USER_ID) as USERS
FROM ONLINE_SALE s
JOIN USER_INFO u ON u.USER_ID = s.USER_ID
WHERE GENDER is not NULL
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER
ORDER BY YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER