SELECT p.PRODUCT_ID, PRODUCT_NAME, (SUM(AMOUNT) * PRICE) as TOTAL_SALES
FROM FOOD_ORDER o
JOIN FOOD_PRODUCT p ON o.PRODUCT_ID = p.PRODUCT_ID
WHERE YEAR(o.PRODUCE_DATE) = 2022 and MONTH(o.PRODUCE_DATE) = 5
GROUP BY PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID