SELECT APNT_NO, PT_NAME, a.PT_NO, a.MCDP_CD, DR_NAME, APNT_YMD
FROM APPOINTMENT a
LEFT JOIN PATIENT p ON a.PT_NO = p.PT_NO
LEFT JOIN DOCTOR d ON a.MDDR_ID = d.DR_ID
WHERE DATEDIFF(APNT_YMD, '2022-04-13') = 0 AND a.MCDP_CD = 'CS' AND APNT_CNCL_YN = 'N'
ORDER BY APNT_YMD