SELECT e.EMP_NO, e.EMP_NAME,
(CASE
    WHEN AVG(SCORE) >= 96 THEN 'S'
    WHEN AVG(SCORE) >= 90 THEN 'A'
    WHEN AVG(SCORE) >= 80 THEN 'B'
    ELSE 'C' END
) as GRADE,
(CASE
    WHEN AVG(SCORE) >= 96 THEN e.SAL * 0.2
    WHEN AVG(SCORE) >= 90 THEN e.SAL * 0.15
    WHEN AVG(SCORE) >= 80 THEN e.SAL * 0.10
    ELSE 0 END
) as BONUS
FROM HR_GRADE g, HR_EMPLOYEES e
WHERE g.EMP_NO = e.EMP_NO
GROUP BY EMP_NO
ORDER BY EMP_NO