SELECT MEMBER_NAME, REVIEW_TEXT, REVIEW_DATE
FROM REST_REVIEW r
JOIN MEMBER_PROFILE m ON m.MEMBER_ID = r.MEMBER_ID
WHERE r.MEMBER_ID = (SELECT MEMBER_ID FROM REST_REVIEW GROUP BY MEMBER_ID ORDER BY COUNT(*) DESC LIMIT 1)
ORDER BY REVIEW_DATE, REVIEW_TEXT