SELECT YEAR(DIFFERENTIATION_DATE) as YEAR, 
    (SELECT MAX(SIZE_OF_COLONY) FROM ECOLI_DATA b WHERE YEAR(a.DIFFERENTIATION_DATE) = YEAR(b.DIFFERENTIATION_DATE) GROUP BY YEAR(DIFFERENTIATION_DATE)) - SIZE_OF_COLONY as YEAR_DEV, ID
FROM ECOLI_DATA a
ORDER BY YEAR, YEAR_DEV