SELECT SUM(SCORE), e.EMP_NO, e.EMP_NAME, e.POSITION, e.EMAIL
FROM HR_EMPLOYEES e, HR_GRADE g
WHERE e.EMP_NO = g.EMP_NO
GROUP BY EMP_NO HAVING SUM(SCORE) = (SELECT MAX(total) FROM (SELECT SUM(SCORE) as total FROM HR_GRADE GROUP BY EMP_NO) as temp)