-- 코드를 입력하세요
SELECT b.TITLE, b.BOARD_ID, r.REPLY_ID, r.WRITER_ID, r.CONTENTS, r.CREATED_DATE
FROM USED_GOODS_BOARD b, USED_GOODS_REPLY r
WHERE b.BOARD_ID = r.BOARD_ID and YEAR(b.CREATED_DATE) = 2022 and MONTH(b.CREATED_DATE) = 10
ORDER BY r.CREATED_DATE, b.TITLE