SELECT CONCAT('/home/grep/src/', f.BOARD_ID, '/', FILE_ID, FILE_NAME, FILE_EXT) as FILE_PATH 
FROM USED_GOODS_BOARD b, USED_GOODS_FILE f
WHERE b.VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD) AND b.BOARD_ID = f.BOARD_ID
ORDER BY FILE_ID DESC