SELECT CATEGORY, PRICE as MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT a
WHERE CATEGORY IN ('과자', '국', '김치', '식용유') and 
    PRICE = (SELECT MAX(PRICE) FROM FOOD_PRODUCT b WHERE a.CATEGORY = b.CATEGORY GROUP BY CATEGORY)
GROUP BY CATEGORY
ORDER BY PRICE DESC