SELECT CASE
            WHEN (d.SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python')) > 0
                and (d.SKILL_CODE & (SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY = 'Front End')) > 0
                THEN 'A'
            WHEN (d.SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#')) > 0 THEN 'B'
            WHEN (d.SKILL_CODE & (SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY = 'Front End' GROUP BY CATEGORY)) > 0
                THEN 'C'
        END as GRADE, ID, EMAIL 
FROM DEVELOPERS d
GROUP BY ID HAVING GRADE is not NULL
ORDER BY GRADE, ID